### ISSUE TITLE
想跟您请教lab system的服务端问题

### ISSUE THREAD

**Issue by vastgod-zhang** [fwgood/LabSystem#3]
您好！在github上关注到您基于vue的lab system项目，想学习一下。但是您项目文件中server文件夹为空，不知放不方便分享一下！感谢！

**Comment by fwgood** [comment]
由于年代久远，后端代码已经丢失，请参考另一项目
[lab-back](https://github.com/fwgood/lab-back)
[lab-front](https://github.com/fwgood/lab-front)
